version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: change-me
      POSTGRES_DB: kanevskyDB
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

#services:
#  mysql:
#    image: mysql:latest
#    container_name: mysql_db
#    environment:
#      MYSQL_ROOT_PASSWORD: change-me
#      MYSQL_DATABASE: kanevskyDB
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./mysql-data:/var/lib/mysql
#    networks:
#      - backend

networks:
  backend: